import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";
import { relations } from "drizzle-orm";

/**
 * Messages table definition.
 *
 * Stores all messages received from the network. This table captures both
 * original messages and relayed messages, with metadata to distinguish
 * between them.
 *
 * Columns:
 * - id: Primary key. Unique integer identifier for the message record.
 * - type: Type of the message (e.g., "text", "media", "command").
 * - topic: The network topic/channel that the message was broadcasted into.
 * - isRelay: Boolean flag indicating whether the sender is acting as a relay
 *   (broadcasting someone else's message) rather than the original creator.
 *   Stored as integer (0/1) in SQLite.
 * - senderPublicKey: Public key of the immediate sender who transmitted
 *   this message to the network. This may differ from the actual creator
 *   when isRelay is true.
 * - broadcastTimestamp: Unix timestamp indicating when the message was
 *   broadcasted by the immediate sender.
 * - timestamp: Unix timestamp indicating when the message was originally
 *   sent/created (not when it was received or relayed).
 * - nonce: Unique identifier for the message, typically generated by the
 *   original creator to prevent replay attacks.
 * - messageOwnerPublicKey: Public key of the actual creator/originator
 *   of the message content. This identifies who originally authored the
 *   message, regardless of who relayed it.
 * - signature: Cryptographic signature of the message payload, signed by
 *   the messageOwnerPrivateKey. Used to verify message authenticity and
 *   integrity.
 * - payload: Stringified JSON containing the actual message content and
 *   any additional metadata. The structure of this JSON is defined by
 *   the message type.
 */
export const messages = sqliteTable("messages", {
  id: integer("id").primaryKey(),
  
  type: text("type").notNull(),
  topic: text("topic").notNull(),
  
  isRelay: integer("is_relay").notNull(), // 0/1 for false/true
  
  senderPublicKey: text("sender_public_key").notNull(),
  broadcastTimestamp: integer("broadcast_timestamp").notNull(),
  messageTimestamp: integer("timestamp").notNull(),
  nonce: text("nonce").notNull().unique(),
  
  messageOwnerPublicKey: text("message_owner_public_key").notNull(),
  signature: text("signature").notNull(),
  
  payload: text("payload").notNull(),
});

/**
 * Relations for the `messages` table.
 *
 * Currently defined as empty but can be extended to include:
 * - Space relationships (if messages are associated with spaces)
 * - User/profile relationships
 * - Parent/child relationships for threaded messages
 */
export const messagesRelations = relations(messages, ({}) => ({}));