import { sqliteTable, text, integer, index, uniqueIndex } from "drizzle-orm/sqlite-core";

/**
 * Messages table definition.
 *
 * Stores all messages received from the network. This table captures both
 * original messages and relayed messages, with metadata to distinguish
 * between them.
 *
 * Columns:
 * - id: Primary key. Unique integer identifier for the message record.
 * 
 * - type: Type of the message (e.g., "text", "media", "command").
 * 
 * - spaceId: ID of the space this message is assigned to.
 * 
 * - senderPublicKey: Public key of the immediate sender who transmitted
 *   this message to the network. This may differ from the actual creator
 *   when isRelay is true.
 * 
 * - broadcastTimestamp: Unix timestamp indicating when the message was
 *   broadcasted by the immediate sender.
 * 
 * - messageTimestamp: Unix timestamp indicating when the message was originally
 *   sent/created (not when it was received or relayed).
 * 
 * - ownerPublicKey: Public key of the actual creator/originator
 *   of the message content. This identifies who originally authored the
 *   message, regardless of who relayed it.
 * 
 * - nonce: Unique identifier for the message, typically generated by the
 *   original creator to prevent replay attacks.
 * 
 * - signature: Cryptographic signature of the message payload, signed by
 *   the messageOwnerPrivateKey. Used to verify message authenticity and
 *   integrity.
 * 
 * - payload: Stringified JSON containing the actual message content and
 *   any additional metadata. The structure of this JSON is defined by
 *   the message type.
 */
export const messages = sqliteTable("messages", {
  id: integer("id").primaryKey(),

  messageId: text("message_id").notNull(),
  spaceId: integer("space_id").notNull(),

  type: text("type").notNull(),

  // broadcaster properties
  senderPublicKey: text("sender_public_key").notNull(),
  broadcastTimestamp: integer("broadcast_timestamp").notNull(),

  // message owner properties
  ownerPublicKey: text("message_owner_public_key").notNull(),
  messageTimestamp: integer("timestamp").notNull(),
  nonce: text("nonce").notNull().unique(),
  signature: text("signature").notNull(),
  payload: text("payload").notNull(),

}, (table) => [
  uniqueIndex("messages_message_id_unique").on(table.messageId),
  index("message_space_range_index").on(
    table.spaceId,
    table.messageTimestamp,
    table.messageId
  )
]);